[package]
name = "rustracer"
version = "0.1.0"
authors = ["Alexandre"]
edition = "2021"

[dependencies]
image = "0.24.1"
serde = "1.0.126"
rulinalg = "0.4.2"
crossbeam = "0.8.0"
serde_json = "1.0.49"
